name: DiverDataProcessor
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas>=2.2.3,<3
  - geopandas>=1.0.1,<2
  - xarray>=2025.1.0,<2026
  - rioxarray>=0.17.0,<0.18
  - numpy>=2.2.1,<3
  - pip>=24.3.1,<25
  - contextily>=1.6.2,<2
  - openpyxl>=3.1.5,<4